name: app

on:
  push:
    branches: [ "main" ]
    paths:
      - pack/version.txt
      
jobs:
  build:
    runs-on: windows-latest 
    env:
      EnvData: hello
    steps:
    - name: Invoke
      run: ./pack/test.bat
