name: app

on:
  push:
    branches: [ "main" ]
    paths:
      - pack/version.txt
      
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest 
    env:
      EnvData: hello
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Invoke
      run: ./pack/test.bat

    - name: release
      uses: ncipollo/release-action@v1
      with:
        tag: "v0.0.4"
        artifacts: "pack/files/*"
        bodyFile: "pack/body.md"