name: app

on:
  push:
    branches: [ "main" ]
    paths:
      - pack/version.txt
      
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest 
    outputs:
      version: ${{ steps.versionStep.outputs.version }}
    env:
      EnvData: hello
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SetVersion
      id: versionStep
      run: $GITHUB_OUTPUT = "version=$(cat pack/version.txt)"

    - name: GetVersion
      run: write-output 123 $GITHUB_OUTPUT ${{ needs.build.outputs.version }} 234

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Invoke
      run: ./pack/test.bat

    - name: release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.build.outputs.version }}
        artifacts: "pack/files/*.txt"
        bodyFile: "pack/body.md"