name: sync

on:
  workflow_run:
    workflows: ["release"]
    types: [completed]
      
jobs:
  build:
    permissions: write-all
    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Test
      run: echo 'ok'